[project]
name = "psh"
version = "0.1.0"
description = "Evaluating PSH"
authors = ["Chris McComb <ccm@cmu.edu>"]
license = "MIT"
dependencies = [
    "pandas>=1.5.0",
    "gradio>=42.0.0"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
